WebMusync/MusyncUI/Models/Sync/YaPlaylist.cs
namespace Tolltech.MusyncUI.Models.Sync
{
    public class YaPlaylist
    {
        public string Title { get; set; }
        public string Id { get; set; }
    }
}

WebMusync/MusyncUI/Models/Sync/YaPlaylists.cs
using System;

namespace Tolltech.MusyncUI.Models.Sync
{
    public class YaPlaylists
    {
        public YaPlaylists()
        {
            Playlists = Array.Empty<YaPlaylist>();
        }

        public YaPlaylist[] Playlists { get; set; }
    }
}

WebMusync/MusyncUI/Controllers/SyncController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Tolltech.Musync.Domain;
using Tolltech.Musync.Models;
using Tolltech.Musync.Settings;
using Tolltech.MusyncUI.Filters;
using Tolltech.MusyncUI.Implementaitions;
using Tolltech.MusyncUI.Implementaitions.Common;
using Tolltech.MusyncUI.Implementaitions.Extensions;
using Tolltech.MusyncUI.Implementaitions.Sync;
using Tolltech.MusyncUI.Implementaitions.Users;
using Tolltech.MusyncUI.Models.Sync;

namespace Tolltech.MusyncUI.Controllers
{
    [NoCache]
    public class SyncController : BaseController
    {
        private readonly ITrackGetter trackGetter;
        private readonly IYandexService yandexService;
        private readonly IAuthorizationSettings authorizationSettings;
        private readonly IDomainService domainService;
        private readonly IProgressBar progressBar;
        private readonly IImportResultLogger importResultLogger;

        public SyncController(ITrackGetter trackGetter, IYandexService yandexService,
            IAuthorizationSettings authorizationSettings, INoteUserService noteUserService,
            IDomainService domainService,
            IProgressBar progressBar,
            IImportResultLogger importResultLogger) : base(noteUserService)
        {
            this.trackGetter = trackGetter;
            this.yandexService = yandexService;
            this.authorizationSettings = authorizationSettings;
            this.domainService = domainService;
            this.progressBar = progressBar;
            this.importResultLogger = importResultLogger;
        }

        [HttpPost]
        public ActionResult AuthorizeVk(AuthorizeForm authorizeForm)
        {
            var authInfo = authorizationSettings.GetCachedMuserAuthorization(UserId);
            if (authInfo == null)
            {
                authInfo = new MuserAuthorization
                {
                    VkLogin = authorizeForm.Login,
                    VkPassword = authorizeForm.Pass
                };
            }
            else
            {
                authInfo.VkLogin = authorizeForm.Login;
                authInfo.VkPassword = authorizeForm.Pass;
            }

            authorizationSettings.SetMuserAuthorization(string.Empty, authInfo, UserId);


            return PartialView("AuthorizeResult", new AuthorizeResult {Success = true});
        }

        [HttpPost]
        public void UnauthorizeYa()
        {
            var authInfo = authorizationSettings.GetCachedMuserAuthorization(UserId);
            if (authInfo == null)
            {
                return;
            }
            else
            {
                authInfo.YaLogin = string.Empty;
                authInfo.YaPassword = string.Empty;
            }

            authorizationSettings.SetMuserAuthorization(string.Empty, authInfo, UserId);
        }

        [HttpPost]
        public async Task<ActionResult> AuthorizeYa(AuthorizeForm authorizeForm)
        {
            var success = await yandexService.CheckCredentialsAsync(authorizeForm.Login, authorizeForm.Pass)
                .ConfigureAwait(true);

            Response.SetCookies(Constants.YaLoginCookie, authorizeForm.Login ?? string.Empty);

            if (!success)
            {
                return PartialView("AuthorizeResult", new AuthorizeResult {Success = false});
            }

            var authInfo = authorizationSettings.GetCachedMuserAuthorization(UserId);
            if (authInfo == null)
            {
                authInfo = new MuserAuthorization
                {
                    YaLogin = authorizeForm.Login,
                    YaPassword = authorizeForm.Pass
                };
            }
            else
            {
                authInfo.YaLogin = authorizeForm.Login;
                authInfo.YaPassword = authorizeForm.Pass;
            }

            authorizationSettings.SetMuserAuthorization(string.Empty, authInfo, UserId);

            return await GetYaPlaylists().ConfigureAwait(true);
        }

        [HttpGet]
        public async Task<ActionResult> GetVkTracks(VkForm form)
        {
            var tracks = await trackGetter.GetTracksAsync(form.AudioString).ConfigureAwait(true);

            Response.SetCookies(Constants.VkUrlCookie, form.AudioString ?? string.Empty);

            return PartialView("Tracks", tracks);
        }

        [HttpGet]
        public async Task<ActionResult> GetNewVkTracks(string audioStr, string yaPlaylistId)
        {
            var audioUrl = trackGetter.GetAudioUrl(audioStr);
            var tracks = await domainService.GetNewVkTracksUnauthorizedAsync(yaPlaylistId, UserId, audioUrl).ConfigureAwait(true);
            return PartialView("Tracks", tracks.ToTracksModel());
        }


        [HttpPost]
        public async Task<ActionResult> ImportTracks(TrackImportForm tracksForm)
        {
            var trackToImport = tracksForm.Tracks.Tracks
                .Select(x => new VkTrack
                {
                    Artist = x.Artist,
                    Title = x.Title,
                })
                .Reverse()
                .ToArray();

            var progressId = Guid.NewGuid();

            var results = await domainService.ImportTracksAsync(trackToImport, tracksForm.YaPlaylistId, UserId, tuple =>
                progressBar.UpdateProgressModel(new ProgressModel
                {
                    Id = progressId,
                    Proecssed = tuple.Processed,
                    Total = tuple.Total
                })).ConfigureAwait(true);

            importResultLogger.WriteImportLogs(results, UserId);

            return PartialView("Progress", progressBar.GetProgressModel(progressId));
        }

        [HttpGet]
        public ActionResult GetProgress(Guid progressId)
        {
            return PartialView("Progress", progressBar.GetProgressModel(progressId));
        }

        [HttpGet]
        public async Task<ActionResult> GetYaPlaylists()
        {
            var client = await yandexService.GetClientAsync(UserId).ConfigureAwait(true);

            var playlists = await client.GetPlaylistsAsync().ConfigureAwait(true);

            return PartialView("YaPlaylists", new YaPlaylists
            {
                Playlists = playlists
                    .Select(x => new YaPlaylist
                    {
                        Title = x.Title,
                        Id = x.Id
                    })
                    .ToArray()
            });
        }

        [HttpGet]
        public async Task<ActionResult> GetYaTracks(string yaPlaylistId)
        {
            var client = await yandexService.GetClientAsync(UserId).ConfigureAwait(true);

            var tracks = await client.GetTracksAsync(yaPlaylistId).ConfigureAwait(true);

            return PartialView("Tracks", tracks.ToTracksModel());
        }
    }
}

WebMusync/MusyncUI/Views/Shared/FileUpload.cshtml
@model string
<div class="divUploads">
    <div class="divUploadImg">
    </div>
    @Html.Hidden("Images", string.Join(",", string.IsNullOrEmpty(Model) ? "" : Model))
    <input type="file" class="fileUpload" accept="image/jpeg,image/png,image/bmp,image/jpg, jpg|png|jpeg|bmp" name="image" data_val="false" />
</div>

<script type="text/javascript">
    if (InitFileUploads)
        InitFileUploads();
</script>

WebMusync/MusyncUI/Views/Shared/Progress.cshtml
@model Tolltech.MusyncUI.Models.Sync.ProgressModel

WebMusync/MusyncUI/Views/Shared/Tracks.cshtml
@model Tolltech.MusyncUI.Models.Sync.TracksModel
<div>
    @Html.ListBoxFor(x => x.Tracks, Model.Tracks.Select(x => new SelectListItem
{
    Text = x.Artist + " - " + x.Title,
    Value = Json.Encode(x)
}), new{style= "max-width:500px;min-width:300px;height:500px;line-height:500px;" })
</div>

WebMusync/MusyncUI/Views/Shared/YaPlaylists.cshtml
@model Tolltech.MusyncUI.Models.Sync.YaPlaylists

@using (Ajax.BeginForm("GetYaTracks", "Sync", new AjaxOptions
{
    UpdateTargetId = "yaTracks",
    InsertionMode = InsertionMode.Replace,
    HttpMethod = "GET",
    OnSuccess = "YaSuccess(data)",
    OnFailure = "YaFail()",    
}, new {id = "yaPlaylistForm"}))
{
    @Html.DropDownList("yaPlaylistId", Model.Playlists.Select(x => new SelectListItem
    {
        Value = x.Id,
        Text = x.Title,
        Selected = x.Title == "Vk"
    }), new {id = "yaPlaylists"})    
}

WebMusync/MusyncUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <title>@ViewBag.Title</title>
</head>
<body>
    <header>
        @*        <div class="content-wrapper">
            <div class="float-left">
            </div>
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
            </div>
        </div>*@
        <table style="width: 100%; background-color: black" class="bodyTable">
            <tr>
                <td style="width: 15%"></td>
                <td style="width: 70%">
                    <a href="http://musync.ru">
                        <img src="~/Images/musyncLogoTrans.png" style="width: 250px; float: left;">
                    </a>
                    <div class="content-wrapper">
                        <div class="float-left">
                        </div>
                        <div class="float-right" style="color: #AAA">
                            <section id="login">
                                @Html.Partial("_LoginPartial")
                            </section>
                        </div>
                    </div>
                </td>
                <td style="width: 15%" />
            </tr>
        </table>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <div>
            <table style="width: 100%" class="bodyTable">
                <tr class="bodyTableth">
                    <td />
                    <td>
                        @*@RenderSection("NoteMenu", required: false)*@
                    </td>
                    <td />
                </tr>
                <tr>
                    <td style="" />
                    <td style="width: 1%">
                        @RenderBody()
                    </td>
                    <td style="" />
                </tr>
            </table>
        </div>
    </div>
    <footer>
        <div class="content-wrapper">
            <span class="float-left" style="display: flexbox">
                <a href="mailto:alexandrovpe@gmail.com" style="color: #AAA">alexandrovpe@gmail.com</a>
                <span style="color: #AAA">&copy; @DateTime.Now.Year</span>
            </span>
        </div>
    </footer>   
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/controls")
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        HashTags(".tagbox", "tagMenuId");
        $(document).ready(function() {
            InitFileUploads();
        });
        SyncControl('@Url.Action("GetNewVkTracks", "Sync")','@Url.Action("ImportTracks", "Sync")');
    </script>
</body>
</html>


@*<!DOCTYPE html>
<html lang="en">
<head>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
            </div>
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <div>
            <div class="bodyTable g-100">
                <div class="bodyTableth g-row">
                    <div class="g-col-1 g-span-15"></div>
                    <div class="g-col-16 g-span-70">
                        @RenderSection("NoteMenu", required: false)
                    </div>
                    <div class="g-col-86 g-span-15"></div>
                </div>
                <div class="g-row">
                    <div class="g-col-1 g-span-15"></div>
                    <div class="g-col-16 g-span-70">
                        @RenderBody()
                    </div>
                    <div class="g-col-86 g-span-15"></div>
                </div>
            </div>
        </div>
    </div>
    <footer>
        <div class="content-wrapper">
            <span class="float-left" style="display: flexbox">
                <a href="mailto:alexandrovpe@gmail.com">alexandrovpe@gmail.com</a>
                <span>&copy; @DateTime.Now.Year</span>
            </span>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
    @RenderSection("scripts", required: false)
</body>
</html>
*@